
services:
  vpn:
    image: thrnz/docker-wireguard-pia
    volumes:
      - ./pia:/pia
      - ./pia-shared:/pia-shared
      - ./set_qbt_port.sh:/set_qbt_port.sh
    ports:
      - 8080:8080
      - 9696:9696
    cap_add:
      - NET_ADMIN
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - LOC=${PIA_LOC}
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - PORT_FORWARDING=1
      - KEEPALIVE=25
      - PORT_PERSIST=1
      - PORT_SCRIPT=${PORT_SCRIPT}
      - QBT_USER=${QBT_USER}
      - QBT_PASS=$(QBT_PASS)
      - QBT_PORT=${QBT_PORT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - UMASK=002
    volumes:
      - ./docker/appdata/qbittorrent:/config
      - /mnt/sdb1/data/torrents:/data/torrents
    restart: unless-stopped
    network_mode: "service:vpn"
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ./docker/appdata/plexconfig:/config
      - /mnt/sdb1/data/media:/data/media
    restart: unless-stopped
    depends_on:
      vpn:
        condition: service_healthy
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/appdata/radarr:/config
      - /mnt/sdb1/data:/data
    restart: unless-stopped
    depends_on:
      - qbittorrent
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/appdata/sonarr:/config
      - /mnt/sdb1/data:/data
    restart: unless-stopped
    depends_on:
      - qbittorrent
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ./docker/appdata/prowlarr:/config
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - qbittorrent
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ./docker/appdata/overseerr:/config
    restart: unless-stopped
    depends_on:
      - qbittorrent
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}
    depends_on:
      - overseerr
networks:
  vpn:
